# Generated by Django 5.0 on 2024-01-19 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("BJT", "BJT"),
                            ("MOSFET", "MOSFET"),
                            ("IGBT", "IGBT"),
                            ("CAPACITOR", "Capacitor"),
                            ("RESISTOR", "Resistor"),
                            ("DIODE", "Diode"),
                            ("INDUCTOR", "Inductor"),
                        ],
                        default="BJT",
                    ),
                ),
                ("component_id", models.IntegerField()),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
