# Generated by Django 5.0 on 2024-01-26 02:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_dsv_mosfet_vds_bjt_product_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mosfet",
            old_name="dsv",
            new_name="vds",
        ),
        migrations.AlterField(
            model_name="bjt",
            name="product_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="capacitor",
            name="product_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="diode",
            name="product_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="igbt",
            name="product_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="inductor",
            name="product_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="mosfet",
            name="product_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="resistor",
            name="product_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
